# Generated by Django 5.1.2 on 2024-11-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=11)),
                ('balance', models.IntegerField()),
                ('picture', models.ImageField(default='fallback.jpg', upload_to='')),
            ],
        ),
    ]
